keys:
  - &io age17jq33fydz8gpsel7y7e5txrydyvyzeuwmpuyntn7r293qdld4f6sd083kd
  - &ganymedes age1_GANYMEDES_HOST_KEY_PLACEHOLDER
  - &nymphe age1d37zv3299va6q8nmqr2fllzsq33pne78mz7dlr57n25h5g4t4e3s9zddyk

creation_rules:
  - path_regex: secrets/vpn\.ovpn$
    key_groups:
      - age:
          - *io
  - path_regex: secrets/dc01_ca\.pem$
    key_groups:
      - age:
          - *io
  - path_regex: secrets/vpn_io\.ovpn$
    key_groups:
      - age:
          - *io
