{ unstable }:
_final: _prev: {
  hyprland = unstable.hyprland;
  hyprland-plugins = unstable.hyprland-plugins;
  hyprpaper = unstable.hyprpaper;
  hypridle = unstable.hypridle;
  hyprlock = unstable.hyprlock;
  hyprpicker = unstable.hyprpicker;
  hyprutils = unstable.hyprutils;
  hyprlang = unstable.hyprlang;
  hyprcursor = unstable.hyprcursor;
  xdg-desktop-portal-hyprland = unstable.xdg-desktop-portal-hyprland;
  nushell = unstable.nushell;
  flameshot = unstable.flameshot;
  noctalia = unstable.noctalia;
  tuigreet = unstable.tuigreet;
  bitwarden-desktop = unstable.bitwarden-desktop;
  opencode = unstable.opencode;
  kdePackages.dolphin = unstable.kdePackages.dolphin;
  kdePackages.dolphin-plugins = unstable.kdePackages.dolphin-plugins;
}
