{
  pkgs,
  ...
}:

{
  environment.systemPackages = with pkgs; [
    exfat
    exfatprogs
    dosfstools
    telegram-desktop
    qbittorrent
    obsidian
    mpv
    unzip
    p7zip
    anki-bin
    libreoffice-fresh
    vesktop
    arrpc
    gparted
    ntfsprogs
    ntfs3g
    dosbox-x
    heroic
    impression
    dig
    nmap
    catppuccin-kvantum
    gruvbox-kvantum
    nemo-with-extensions
    nwg-look
    adw-gtk3
    rewaita
    morewaita-icon-theme
    hyprpicker
    glib
    networkmanagerapplet
    gpu-screen-recorder
    gpu-screen-recorder-gtk
    nh
    nixfmt
    fortune
    zenity
    xdg-desktop-portal-gtk
    cachix
    age
    sops
    busybox
    nurl
    nushell
    tuigreet
    noctalia
    bitwarden-desktop
    opencode
    stremio-linux-shell
    attic-client
    qt6.qtwayland
    kdePackages.dolphin
    kdePackages.dolphin-plugins
    kdePackages.qtstyleplugin-kvantum
    kdePackages.qt6ct
  ];
}
